INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (1, '1234567890', 'nam', 'nguoidung1@email.com', TO_DATE('01-01-1990', 'DD-MM-YYYY'), '0123456789', 'Người Dùng 1', '123 Đường ABC, Thành phố XYZ', 'student', 2);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (2, '0987654321', 'nữ', 'nguoidung2@email.com', TO_DATE('15-05-1985', 'DD-MM-YYYY'), '0987654321', 'Người Dùng 2', '456 Đường XYZ, Thành phố ABC', 'teacher', 3);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (3, '5555555555', 'nam', 'nguoidung3@email.com', TO_DATE('10-10-1995', 'DD-MM-YYYY'), '0555555555', 'Người Dùng 3', '789 Đường MNO, Thành phố PQR', 'student', 2);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (4, '7777777777', 'nữ', 'nguoidung4@email.com', TO_DATE('20-02-1980', 'DD-MM-YYYY'), '0777777777', 'Người Dùng 4', '101 Đường LMN, Thành phố XYZ', 'manager', 1);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (5, '1111111111', 'nam', 'nguoidung5@email.com', TO_DATE('05-03-1993', 'DD-MM-YYYY'), '0111111111', 'Người Dùng 5', '222 Đường UVW, Thành phố XYZ', 'admin', 4);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (6, '2222222222', 'nữ', 'nguoidung6@email.com', TO_DATE('12-06-1988', 'DD-MM-YYYY'), '0222222222', 'Người Dùng Sáu', '456 Đường KLM, Thành phố UVW', 'student', 3);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (7, '3333333333', 'nam', 'nguoidung7@email.com', TO_DATE('03-09-1976', 'DD-MM-YYYY'), '0333333333', 'Người Dùng Bảy', '789 Đường XYZ, Thành phố PQR', 'teacher', 2);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (8, '4444444444', 'nữ', 'nguoidung8@email.com', TO_DATE('28-12-1982', 'DD-MM-YYYY'), '0444444444', 'Người Dùng Tám', '101 Đường RST, Thành phố DEF', 'manager', 4);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (9, '6666666666', 'nam', 'nguoidung9@email.com', TO_DATE('09-07-1990', 'DD-MM-YYYY'), '0666666666', 'Người Dùng Chín', '222 Đường OPQ, Thành phố GHI', 'admin', 1);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (10, '8888888888', 'nữ', 'nguoidung10@email.com', TO_DATE('17-11-1998', 'DD-MM-YYYY'), '0888888888', 'Người Dùng Mười', '333 Đường WXY, Thành phố JKL', 'student', 2);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (11, '9999999999', 'nam', 'nguoidung11@email.com', TO_DATE('22-04-1986', 'DD-MM-YYYY'), '0999999999', 'Người Dùng Mười Một', '444 Đường ABC, Thành phố XYZ', 'teacher', 3);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (12, '1010101010', 'nữ', 'nguoidung12@email.com', TO_DATE('05-03-1995', 'DD-MM-YYYY'), '1010101010', 'Người Dùng Mười Hai', '555 Đường DEF, Thành phố MNO', 'manager', 4);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (13, '1212121212', 'nam', 'nguoidung13@email.com', TO_DATE('11-08-1993', 'DD-MM-YYYY'), '1212121212', 'Người Dùng Mười Ba', '666 Đường GHI, Thành phố PQR', 'admin', 1);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (14, '1313131313', 'nữ', 'nguoidung14@email.com', TO_DATE('19-02-1980', 'DD-MM-YYYY'), '1313131313', 'Người Dùng Mười Bốn', '777 Đường JKL, Thành phố TUV', 'student', 2);
INSERT INTO USER_ (ID, ssn, sex, email, birth, phone, name, address, role, DEPT_ID)
VALUES (15, '1414141414', 'nam', 'nguoidung15@email.com', TO_DATE('06-06-1988', 'DD-MM-YYYY'), '1414141414', 'Người Dùng Mười Lăm', '888 Đường XYZ, Thành phố ABC', 'teacher', 3);
